image:
  repository: tccr.io/truecharts/kavita
  pullPolicy: IfNotPresent
  tag: v0.7.6@sha256:a78a5745b8f6fab8afb3c023e8b32a1a7540f92c5913cbd8d8820ecd9f309c5a
service:
  main:
    ports:
      main:
        targetPort: 5000
        port: 10189
persistence:
  config:
    enabled: true
    mountPath: "/kavita/config"
  manga:
    enabled: true
    mountPath: "/manga"
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
